football_prediction:
  target: ci
  outputs:
    ci:
      type: duckdb
      path: "../db/football.duckdb"
      schema: gold
      threads: 4
      settings:
        preserve_insertion_order: false
        memory_limit: '16GB'
        max_temp_directory_size: '100GB'