intermediate_whoscored_lineup_period:
  end_minute:   {min: 0, max: 130}
  start_minute: {min: 0, max: 130}
intermediate_fbref_keeper:
  save_pct:     {min: 0, max: 100}
intermediate_team_match_backbone:
  np_xg:        {min: 0}
  opponent_id:  {not_null: true}