{{ config(materialized='table', schema='marts') }}

-- ══════════════════════════════════════════════════════════════════════════════
-- mart_assists — grain (match_id, team_id, player_id) — cible assisted (≥1 passe déc.).
-- Population : joueur_saison (tous les joueurs profilés → passeurs de tout poste).
-- Enrichi de :
--   • exposition + tireur de coups de pied arrêtés (joueur_saison)
--   • contexte offensif de l'équipe + défensif de l'adversaire
--     (equipe_match, fenêtres rolling 3/5/10, anti-leakage)
--   • priors de qualité de saison PRÉCÉDENTE (equipe_match, _lag)
-- Label : player_match_stats.n_assists ≥ 1. Pure sélection (aucun calcul).
--
-- Refonte nommage : backbone et equipe_match lus sous leurs nouveaux noms ; les
-- features equipe_match héritent de leur nom source (dec_…, opp_dec_…). Colonnes
-- renommées selon docs/proposition_nommage_definitif.csv : str_match_id,
-- str_team_id, str_player_id, int_assisted.
-- ══════════════════════════════════════════════════════════════════════════════

-- ══ Refonte nommage (préfixe de type en tête de nom : str_, int_, dec_, dt_, bool_) ══
-- Entrées : les modèles amont refondus sont relus via des CTE in_<modèle> qui les
-- remappent vers les noms/types de travail utilisés par la logique ci-dessous
-- (inchangée). Sortie : CTE mdl_out, renommage + cast selon le type logique.

WITH

-- joueur_saison lu sous ses noms refondus, remappé vers les noms de travail du modèle
in_joueur_saison AS (
    SELECT
        str_match_id                                                 AS "match_id",
        CAST(str_team_id AS BIGINT)                                  AS "team_id",
        CAST(str_player_id AS INTEGER)                               AS "player_id",
        dt_date                                                      AS "date",
        str_season                                                   AS "season",
        str_league_source                                            AS "league_source",
        int_n_apps_lag                                               AS "n_apps_lag",
        CAST(int_minutes_lag AS HUGEINT)                             AS "minutes_lag",
        dec_scorer_xg_per90_lag                                      AS "scorer_xg_per90_lag",
        dec_scorer_shots_per90_lag                                   AS "scorer_shots_per90_lag",
        dec_off_chances_created_per90_lag                            AS "off_chances_created_per90_lag",
        dec_off_key_passes_per90_lag                                 AS "off_key_passes_per90_lag",
        dec_off_xg_per_shot_lag                                      AS "off_xg_per_shot_lag",
        dec_def_aerial_win_rate_lag                                  AS "def_aerial_win_rate_lag",
        dec_def_actions_per90_lag                                    AS "def_actions_per90_lag",
        dec_def_errors_per90_lag                                     AS "def_errors_per90_lag",
        dec_player_card_propensity_lag                               AS "player_card_propensity_lag",
        dec_off_xgchain_per90_lag                                    AS "off_xgchain_per90_lag",
        dec_off_xgbuildup_per90_lag                                  AS "off_xgbuildup_per90_lag",
        dec_scorer_team_shot_share_lag                               AS "scorer_team_shot_share_lag",
        CAST(int_scorer_penalty_taker_lag AS HUGEINT)                AS "scorer_penalty_taker_lag",
        CAST(int_scorer_freekick_taker_lag AS HUGEINT)               AS "scorer_freekick_taker_lag",
        dec_def_threat_conceded_per90_lag                            AS "def_threat_conceded_per90_lag",
        dec_scorer_xgot_overperformance_lag                          AS "scorer_xgot_overperformance_lag",
        str_profile_confidence_flag                                  AS "profile_confidence_flag"
    FROM {{ ref('joueur_saison') }}
),

-- player_match_stats lu sous ses noms refondus, remappé vers les noms de travail du modèle
in_player_match_stats AS (
    SELECT
        str_match_id                                                 AS "match_id",
        CAST(str_team_id AS BIGINT)                                  AS "team_id",
        CAST(str_player_id AS INTEGER)                               AS "player_id",
        int_n_actions                                                AS "n_actions",
        dec_xg_contribution                                          AS "xg_contribution",
        int_n_shots                                                  AS "n_shots",
        CAST(int_n_shots_regular_play AS HUGEINT)                    AS "n_shots_regular_play",
        CAST(int_n_shots_individual_play AS HUGEINT)                 AS "n_shots_individual_play",
        CAST(int_n_shot_assists AS HUGEINT)                          AS "n_shot_assists",
        CAST(int_n_key_passes AS HUGEINT)                            AS "n_key_passes",
        CAST(int_n_longballs AS HUGEINT)                             AS "n_longballs",
        CAST(int_n_crosses AS HUGEINT)                               AS "n_crosses",
        CAST(int_n_throughballs AS HUGEINT)                          AS "n_throughballs",
        int_n_progressive_passes                                     AS "n_progressive_passes",
        int_n_tackles                                                AS "n_tackles",
        int_n_tackles_won                                            AS "n_tackles_won",
        int_n_interceptions                                          AS "n_interceptions",
        int_n_ball_recoveries                                        AS "n_ball_recoveries",
        int_n_challenges                                             AS "n_challenges",
        int_n_clearances                                             AS "n_clearances",
        dec_defensive_zone_x                                         AS "defensive_zone_x",
        int_n_touches                                                AS "n_touches",
        dec_pct_z1_c1                                                AS "pct_z1_c1",
        dec_pct_z1_c2                                                AS "pct_z1_c2",
        dec_pct_z1_c3                                                AS "pct_z1_c3",
        dec_pct_z1_c4                                                AS "pct_z1_c4",
        dec_pct_z1_c5                                                AS "pct_z1_c5",
        dec_pct_z2_c1                                                AS "pct_z2_c1",
        dec_pct_z2_c2                                                AS "pct_z2_c2",
        dec_pct_z2_c3                                                AS "pct_z2_c3",
        dec_pct_z2_c4                                                AS "pct_z2_c4",
        dec_pct_z2_c5                                                AS "pct_z2_c5",
        dec_pct_z3_c1                                                AS "pct_z3_c1",
        dec_pct_z3_c2                                                AS "pct_z3_c2",
        dec_pct_z3_c3                                                AS "pct_z3_c3",
        dec_pct_z3_c4                                                AS "pct_z3_c4",
        dec_pct_z3_c5                                                AS "pct_z3_c5",
        dec_pct_z4_c1                                                AS "pct_z4_c1",
        dec_pct_z4_c2                                                AS "pct_z4_c2",
        dec_pct_z4_c3                                                AS "pct_z4_c3",
        dec_pct_z4_c4                                                AS "pct_z4_c4",
        dec_pct_z4_c5                                                AS "pct_z4_c5",
        dec_pct_z5_c1                                                AS "pct_z5_c1",
        dec_pct_z5_c2                                                AS "pct_z5_c2",
        dec_pct_z5_c3                                                AS "pct_z5_c3",
        dec_pct_z5_c4                                                AS "pct_z5_c4",
        dec_pct_z5_c5                                                AS "pct_z5_c5",
        int_n_aerial_duels                                           AS "n_aerial_duels",
        int_n_aerial_won                                             AS "n_aerial_won",
        dec_aerial_win_rate                                          AS "aerial_win_rate",
        int_n_aerial_offensive                                       AS "n_aerial_offensive",
        int_n_aerial_defensive                                       AS "n_aerial_defensive",
        CAST(int_n_errors_lead_to_goal AS HUGEINT)                   AS "n_errors_lead_to_goal",
        CAST(int_n_errors_lead_to_shot AS HUGEINT)                   AS "n_errors_lead_to_shot",
        int_n_yellow_cards                                           AS "n_yellow_cards",
        int_n_second_yellows                                         AS "n_second_yellows",
        int_n_red_cards                                              AS "n_red_cards",
        int_n_actions_blank                                          AS "n_actions_blank",
        int_n_progressive_passes_blank                               AS "n_progressive_passes_blank",
        int_n_defensive_actions_blank                                AS "n_defensive_actions_blank",
        int_n_shots_blank                                            AS "n_shots_blank",
        dec_blank_pct_z1_c1                                          AS "blank_pct_z1_c1",
        dec_blank_pct_z1_c2                                          AS "blank_pct_z1_c2",
        dec_blank_pct_z1_c3                                          AS "blank_pct_z1_c3",
        dec_blank_pct_z1_c4                                          AS "blank_pct_z1_c4",
        dec_blank_pct_z1_c5                                          AS "blank_pct_z1_c5",
        dec_blank_pct_z2_c1                                          AS "blank_pct_z2_c1",
        dec_blank_pct_z2_c2                                          AS "blank_pct_z2_c2",
        dec_blank_pct_z2_c3                                          AS "blank_pct_z2_c3",
        dec_blank_pct_z2_c4                                          AS "blank_pct_z2_c4",
        dec_blank_pct_z2_c5                                          AS "blank_pct_z2_c5",
        dec_blank_pct_z3_c1                                          AS "blank_pct_z3_c1",
        dec_blank_pct_z3_c2                                          AS "blank_pct_z3_c2",
        dec_blank_pct_z3_c3                                          AS "blank_pct_z3_c3",
        dec_blank_pct_z3_c4                                          AS "blank_pct_z3_c4",
        dec_blank_pct_z3_c5                                          AS "blank_pct_z3_c5",
        dec_blank_pct_z4_c1                                          AS "blank_pct_z4_c1",
        dec_blank_pct_z4_c2                                          AS "blank_pct_z4_c2",
        dec_blank_pct_z4_c3                                          AS "blank_pct_z4_c3",
        dec_blank_pct_z4_c4                                          AS "blank_pct_z4_c4",
        dec_blank_pct_z4_c5                                          AS "blank_pct_z4_c5",
        dec_blank_pct_z5_c1                                          AS "blank_pct_z5_c1",
        dec_blank_pct_z5_c2                                          AS "blank_pct_z5_c2",
        dec_blank_pct_z5_c3                                          AS "blank_pct_z5_c3",
        dec_blank_pct_z5_c4                                          AS "blank_pct_z5_c4",
        dec_blank_pct_z5_c5                                          AS "blank_pct_z5_c5",
        int_n_actions_blank_late                                     AS "n_actions_blank_late",
        int_n_progressive_passes_blank_late                          AS "n_progressive_passes_blank_late",
        int_n_defensive_actions_blank_late                           AS "n_defensive_actions_blank_late",
        int_n_shots_blank_late                                       AS "n_shots_blank_late",
        dec_blank_late_pct_z1_c1                                     AS "blank_late_pct_z1_c1",
        dec_blank_late_pct_z1_c2                                     AS "blank_late_pct_z1_c2",
        dec_blank_late_pct_z1_c3                                     AS "blank_late_pct_z1_c3",
        dec_blank_late_pct_z1_c4                                     AS "blank_late_pct_z1_c4",
        dec_blank_late_pct_z1_c5                                     AS "blank_late_pct_z1_c5",
        dec_blank_late_pct_z2_c1                                     AS "blank_late_pct_z2_c1",
        dec_blank_late_pct_z2_c2                                     AS "blank_late_pct_z2_c2",
        dec_blank_late_pct_z2_c3                                     AS "blank_late_pct_z2_c3",
        dec_blank_late_pct_z2_c4                                     AS "blank_late_pct_z2_c4",
        dec_blank_late_pct_z2_c5                                     AS "blank_late_pct_z2_c5",
        dec_blank_late_pct_z3_c1                                     AS "blank_late_pct_z3_c1",
        dec_blank_late_pct_z3_c2                                     AS "blank_late_pct_z3_c2",
        dec_blank_late_pct_z3_c3                                     AS "blank_late_pct_z3_c3",
        dec_blank_late_pct_z3_c4                                     AS "blank_late_pct_z3_c4",
        dec_blank_late_pct_z3_c5                                     AS "blank_late_pct_z3_c5",
        dec_blank_late_pct_z4_c1                                     AS "blank_late_pct_z4_c1",
        dec_blank_late_pct_z4_c2                                     AS "blank_late_pct_z4_c2",
        dec_blank_late_pct_z4_c3                                     AS "blank_late_pct_z4_c3",
        dec_blank_late_pct_z4_c4                                     AS "blank_late_pct_z4_c4",
        dec_blank_late_pct_z4_c5                                     AS "blank_late_pct_z4_c5",
        dec_blank_late_pct_z5_c1                                     AS "blank_late_pct_z5_c1",
        dec_blank_late_pct_z5_c2                                     AS "blank_late_pct_z5_c2",
        dec_blank_late_pct_z5_c3                                     AS "blank_late_pct_z5_c3",
        dec_blank_late_pct_z5_c4                                     AS "blank_late_pct_z5_c4",
        dec_blank_late_pct_z5_c5                                     AS "blank_late_pct_z5_c5",
        int_n_actions_drawing                                        AS "n_actions_drawing",
        int_n_progressive_passes_drawing                             AS "n_progressive_passes_drawing",
        int_n_defensive_actions_drawing                              AS "n_defensive_actions_drawing",
        int_n_shots_drawing                                          AS "n_shots_drawing",
        dec_drawing_pct_z1_c1                                        AS "drawing_pct_z1_c1",
        dec_drawing_pct_z1_c2                                        AS "drawing_pct_z1_c2",
        dec_drawing_pct_z1_c3                                        AS "drawing_pct_z1_c3",
        dec_drawing_pct_z1_c4                                        AS "drawing_pct_z1_c4",
        dec_drawing_pct_z1_c5                                        AS "drawing_pct_z1_c5",
        dec_drawing_pct_z2_c1                                        AS "drawing_pct_z2_c1",
        dec_drawing_pct_z2_c2                                        AS "drawing_pct_z2_c2",
        dec_drawing_pct_z2_c3                                        AS "drawing_pct_z2_c3",
        dec_drawing_pct_z2_c4                                        AS "drawing_pct_z2_c4",
        dec_drawing_pct_z2_c5                                        AS "drawing_pct_z2_c5",
        dec_drawing_pct_z3_c1                                        AS "drawing_pct_z3_c1",
        dec_drawing_pct_z3_c2                                        AS "drawing_pct_z3_c2",
        dec_drawing_pct_z3_c3                                        AS "drawing_pct_z3_c3",
        dec_drawing_pct_z3_c4                                        AS "drawing_pct_z3_c4",
        dec_drawing_pct_z3_c5                                        AS "drawing_pct_z3_c5",
        dec_drawing_pct_z4_c1                                        AS "drawing_pct_z4_c1",
        dec_drawing_pct_z4_c2                                        AS "drawing_pct_z4_c2",
        dec_drawing_pct_z4_c3                                        AS "drawing_pct_z4_c3",
        dec_drawing_pct_z4_c4                                        AS "drawing_pct_z4_c4",
        dec_drawing_pct_z4_c5                                        AS "drawing_pct_z4_c5",
        dec_drawing_pct_z5_c1                                        AS "drawing_pct_z5_c1",
        dec_drawing_pct_z5_c2                                        AS "drawing_pct_z5_c2",
        dec_drawing_pct_z5_c3                                        AS "drawing_pct_z5_c3",
        dec_drawing_pct_z5_c4                                        AS "drawing_pct_z5_c4",
        dec_drawing_pct_z5_c5                                        AS "drawing_pct_z5_c5",
        int_n_actions_drawing_late                                   AS "n_actions_drawing_late",
        int_n_progressive_passes_drawing_late                        AS "n_progressive_passes_drawing_late",
        int_n_defensive_actions_drawing_late                         AS "n_defensive_actions_drawing_late",
        int_n_shots_drawing_late                                     AS "n_shots_drawing_late",
        dec_drawing_late_pct_z1_c1                                   AS "drawing_late_pct_z1_c1",
        dec_drawing_late_pct_z1_c2                                   AS "drawing_late_pct_z1_c2",
        dec_drawing_late_pct_z1_c3                                   AS "drawing_late_pct_z1_c3",
        dec_drawing_late_pct_z1_c4                                   AS "drawing_late_pct_z1_c4",
        dec_drawing_late_pct_z1_c5                                   AS "drawing_late_pct_z1_c5",
        dec_drawing_late_pct_z2_c1                                   AS "drawing_late_pct_z2_c1",
        dec_drawing_late_pct_z2_c2                                   AS "drawing_late_pct_z2_c2",
        dec_drawing_late_pct_z2_c3                                   AS "drawing_late_pct_z2_c3",
        dec_drawing_late_pct_z2_c4                                   AS "drawing_late_pct_z2_c4",
        dec_drawing_late_pct_z2_c5                                   AS "drawing_late_pct_z2_c5",
        dec_drawing_late_pct_z3_c1                                   AS "drawing_late_pct_z3_c1",
        dec_drawing_late_pct_z3_c2                                   AS "drawing_late_pct_z3_c2",
        dec_drawing_late_pct_z3_c3                                   AS "drawing_late_pct_z3_c3",
        dec_drawing_late_pct_z3_c4                                   AS "drawing_late_pct_z3_c4",
        dec_drawing_late_pct_z3_c5                                   AS "drawing_late_pct_z3_c5",
        dec_drawing_late_pct_z4_c1                                   AS "drawing_late_pct_z4_c1",
        dec_drawing_late_pct_z4_c2                                   AS "drawing_late_pct_z4_c2",
        dec_drawing_late_pct_z4_c3                                   AS "drawing_late_pct_z4_c3",
        dec_drawing_late_pct_z4_c4                                   AS "drawing_late_pct_z4_c4",
        dec_drawing_late_pct_z4_c5                                   AS "drawing_late_pct_z4_c5",
        dec_drawing_late_pct_z5_c1                                   AS "drawing_late_pct_z5_c1",
        dec_drawing_late_pct_z5_c2                                   AS "drawing_late_pct_z5_c2",
        dec_drawing_late_pct_z5_c3                                   AS "drawing_late_pct_z5_c3",
        dec_drawing_late_pct_z5_c4                                   AS "drawing_late_pct_z5_c4",
        dec_drawing_late_pct_z5_c5                                   AS "drawing_late_pct_z5_c5",
        int_n_actions_winning                                        AS "n_actions_winning",
        int_n_progressive_passes_winning                             AS "n_progressive_passes_winning",
        int_n_defensive_actions_winning                              AS "n_defensive_actions_winning",
        int_n_shots_winning                                          AS "n_shots_winning",
        dec_winning_pct_z1_c1                                        AS "winning_pct_z1_c1",
        dec_winning_pct_z1_c2                                        AS "winning_pct_z1_c2",
        dec_winning_pct_z1_c3                                        AS "winning_pct_z1_c3",
        dec_winning_pct_z1_c4                                        AS "winning_pct_z1_c4",
        dec_winning_pct_z1_c5                                        AS "winning_pct_z1_c5",
        dec_winning_pct_z2_c1                                        AS "winning_pct_z2_c1",
        dec_winning_pct_z2_c2                                        AS "winning_pct_z2_c2",
        dec_winning_pct_z2_c3                                        AS "winning_pct_z2_c3",
        dec_winning_pct_z2_c4                                        AS "winning_pct_z2_c4",
        dec_winning_pct_z2_c5                                        AS "winning_pct_z2_c5",
        dec_winning_pct_z3_c1                                        AS "winning_pct_z3_c1",
        dec_winning_pct_z3_c2                                        AS "winning_pct_z3_c2",
        dec_winning_pct_z3_c3                                        AS "winning_pct_z3_c3",
        dec_winning_pct_z3_c4                                        AS "winning_pct_z3_c4",
        dec_winning_pct_z3_c5                                        AS "winning_pct_z3_c5",
        dec_winning_pct_z4_c1                                        AS "winning_pct_z4_c1",
        dec_winning_pct_z4_c2                                        AS "winning_pct_z4_c2",
        dec_winning_pct_z4_c3                                        AS "winning_pct_z4_c3",
        dec_winning_pct_z4_c4                                        AS "winning_pct_z4_c4",
        dec_winning_pct_z4_c5                                        AS "winning_pct_z4_c5",
        dec_winning_pct_z5_c1                                        AS "winning_pct_z5_c1",
        dec_winning_pct_z5_c2                                        AS "winning_pct_z5_c2",
        dec_winning_pct_z5_c3                                        AS "winning_pct_z5_c3",
        dec_winning_pct_z5_c4                                        AS "winning_pct_z5_c4",
        dec_winning_pct_z5_c5                                        AS "winning_pct_z5_c5",
        int_n_actions_winning_late                                   AS "n_actions_winning_late",
        int_n_progressive_passes_winning_late                        AS "n_progressive_passes_winning_late",
        int_n_defensive_actions_winning_late                         AS "n_defensive_actions_winning_late",
        int_n_shots_winning_late                                     AS "n_shots_winning_late",
        dec_winning_late_pct_z1_c1                                   AS "winning_late_pct_z1_c1",
        dec_winning_late_pct_z1_c2                                   AS "winning_late_pct_z1_c2",
        dec_winning_late_pct_z1_c3                                   AS "winning_late_pct_z1_c3",
        dec_winning_late_pct_z1_c4                                   AS "winning_late_pct_z1_c4",
        dec_winning_late_pct_z1_c5                                   AS "winning_late_pct_z1_c5",
        dec_winning_late_pct_z2_c1                                   AS "winning_late_pct_z2_c1",
        dec_winning_late_pct_z2_c2                                   AS "winning_late_pct_z2_c2",
        dec_winning_late_pct_z2_c3                                   AS "winning_late_pct_z2_c3",
        dec_winning_late_pct_z2_c4                                   AS "winning_late_pct_z2_c4",
        dec_winning_late_pct_z2_c5                                   AS "winning_late_pct_z2_c5",
        dec_winning_late_pct_z3_c1                                   AS "winning_late_pct_z3_c1",
        dec_winning_late_pct_z3_c2                                   AS "winning_late_pct_z3_c2",
        dec_winning_late_pct_z3_c3                                   AS "winning_late_pct_z3_c3",
        dec_winning_late_pct_z3_c4                                   AS "winning_late_pct_z3_c4",
        dec_winning_late_pct_z3_c5                                   AS "winning_late_pct_z3_c5",
        dec_winning_late_pct_z4_c1                                   AS "winning_late_pct_z4_c1",
        dec_winning_late_pct_z4_c2                                   AS "winning_late_pct_z4_c2",
        dec_winning_late_pct_z4_c3                                   AS "winning_late_pct_z4_c3",
        dec_winning_late_pct_z4_c4                                   AS "winning_late_pct_z4_c4",
        dec_winning_late_pct_z4_c5                                   AS "winning_late_pct_z4_c5",
        dec_winning_late_pct_z5_c1                                   AS "winning_late_pct_z5_c1",
        dec_winning_late_pct_z5_c2                                   AS "winning_late_pct_z5_c2",
        dec_winning_late_pct_z5_c3                                   AS "winning_late_pct_z5_c3",
        dec_winning_late_pct_z5_c4                                   AS "winning_late_pct_z5_c4",
        dec_winning_late_pct_z5_c5                                   AS "winning_late_pct_z5_c5",
        int_n_actions_losing                                         AS "n_actions_losing",
        int_n_progressive_passes_losing                              AS "n_progressive_passes_losing",
        int_n_defensive_actions_losing                               AS "n_defensive_actions_losing",
        int_n_shots_losing                                           AS "n_shots_losing",
        dec_losing_pct_z1_c1                                         AS "losing_pct_z1_c1",
        dec_losing_pct_z1_c2                                         AS "losing_pct_z1_c2",
        dec_losing_pct_z1_c3                                         AS "losing_pct_z1_c3",
        dec_losing_pct_z1_c4                                         AS "losing_pct_z1_c4",
        dec_losing_pct_z1_c5                                         AS "losing_pct_z1_c5",
        dec_losing_pct_z2_c1                                         AS "losing_pct_z2_c1",
        dec_losing_pct_z2_c2                                         AS "losing_pct_z2_c2",
        dec_losing_pct_z2_c3                                         AS "losing_pct_z2_c3",
        dec_losing_pct_z2_c4                                         AS "losing_pct_z2_c4",
        dec_losing_pct_z2_c5                                         AS "losing_pct_z2_c5",
        dec_losing_pct_z3_c1                                         AS "losing_pct_z3_c1",
        dec_losing_pct_z3_c2                                         AS "losing_pct_z3_c2",
        dec_losing_pct_z3_c3                                         AS "losing_pct_z3_c3",
        dec_losing_pct_z3_c4                                         AS "losing_pct_z3_c4",
        dec_losing_pct_z3_c5                                         AS "losing_pct_z3_c5",
        dec_losing_pct_z4_c1                                         AS "losing_pct_z4_c1",
        dec_losing_pct_z4_c2                                         AS "losing_pct_z4_c2",
        dec_losing_pct_z4_c3                                         AS "losing_pct_z4_c3",
        dec_losing_pct_z4_c4                                         AS "losing_pct_z4_c4",
        dec_losing_pct_z4_c5                                         AS "losing_pct_z4_c5",
        dec_losing_pct_z5_c1                                         AS "losing_pct_z5_c1",
        dec_losing_pct_z5_c2                                         AS "losing_pct_z5_c2",
        dec_losing_pct_z5_c3                                         AS "losing_pct_z5_c3",
        dec_losing_pct_z5_c4                                         AS "losing_pct_z5_c4",
        dec_losing_pct_z5_c5                                         AS "losing_pct_z5_c5",
        int_n_actions_losing_late                                    AS "n_actions_losing_late",
        int_n_progressive_passes_losing_late                         AS "n_progressive_passes_losing_late",
        int_n_defensive_actions_losing_late                          AS "n_defensive_actions_losing_late",
        int_n_shots_losing_late                                      AS "n_shots_losing_late",
        dec_losing_late_pct_z1_c1                                    AS "losing_late_pct_z1_c1",
        dec_losing_late_pct_z1_c2                                    AS "losing_late_pct_z1_c2",
        dec_losing_late_pct_z1_c3                                    AS "losing_late_pct_z1_c3",
        dec_losing_late_pct_z1_c4                                    AS "losing_late_pct_z1_c4",
        dec_losing_late_pct_z1_c5                                    AS "losing_late_pct_z1_c5",
        dec_losing_late_pct_z2_c1                                    AS "losing_late_pct_z2_c1",
        dec_losing_late_pct_z2_c2                                    AS "losing_late_pct_z2_c2",
        dec_losing_late_pct_z2_c3                                    AS "losing_late_pct_z2_c3",
        dec_losing_late_pct_z2_c4                                    AS "losing_late_pct_z2_c4",
        dec_losing_late_pct_z2_c5                                    AS "losing_late_pct_z2_c5",
        dec_losing_late_pct_z3_c1                                    AS "losing_late_pct_z3_c1",
        dec_losing_late_pct_z3_c2                                    AS "losing_late_pct_z3_c2",
        dec_losing_late_pct_z3_c3                                    AS "losing_late_pct_z3_c3",
        dec_losing_late_pct_z3_c4                                    AS "losing_late_pct_z3_c4",
        dec_losing_late_pct_z3_c5                                    AS "losing_late_pct_z3_c5",
        dec_losing_late_pct_z4_c1                                    AS "losing_late_pct_z4_c1",
        dec_losing_late_pct_z4_c2                                    AS "losing_late_pct_z4_c2",
        dec_losing_late_pct_z4_c3                                    AS "losing_late_pct_z4_c3",
        dec_losing_late_pct_z4_c4                                    AS "losing_late_pct_z4_c4",
        dec_losing_late_pct_z4_c5                                    AS "losing_late_pct_z4_c5",
        dec_losing_late_pct_z5_c1                                    AS "losing_late_pct_z5_c1",
        dec_losing_late_pct_z5_c2                                    AS "losing_late_pct_z5_c2",
        dec_losing_late_pct_z5_c3                                    AS "losing_late_pct_z5_c3",
        dec_losing_late_pct_z5_c4                                    AS "losing_late_pct_z5_c4",
        dec_losing_late_pct_z5_c5                                    AS "losing_late_pct_z5_c5",
        int_n_assists                                                AS "n_assists",
        int_n_chances_created                                        AS "n_chances_created",
        CAST(int_minutes_played AS HUGEINT)                          AS "minutes_played",
        dt_date                                                      AS "date",
        str_season                                                   AS "season",
        str_league_source                                            AS "league_source",
        CAST(dt_scraped_at AS VARCHAR)                               AS "scraped_at"
    FROM {{ ref('player_match_stats') }}
),

mdl_body AS (
with backbone_in as (
    select
        str_match_id                       as match_id,
        cast(str_team_id as bigint)       as team_id,
        str_opponent_id,
        str_venue
    from {{ ref('backbone') }}
)

select
    js.match_id                        as str_match_id,
    cast(js.team_id as varchar)        as str_team_id,
    cast(js.player_id as varchar)      as str_player_id,
    js.season,
    case when b.str_venue = 'Home' then true else false end as is_home,
    cast(b.str_opponent_id as bigint) as opponent_id,

    -- ── Profil du passeur + exposition (joueur_saison) ───────────────────────
    js.scorer_xg_per90_lag,
    js.scorer_shots_per90_lag,
    js.off_chances_created_per90_lag,
    js.off_key_passes_per90_lag,
    js.off_xgchain_per90_lag,
    js.off_xgbuildup_per90_lag,
    js.n_apps_lag,
    js.minutes_lag,
    js.scorer_freekick_taker_lag,
    js.profile_confidence_flag,

    -- ── Contexte offensif de l'ÉQUIPE (equipe_match, rolling anti-leakage) ────
    em.dec_avg_np_xg_rolling_3,  em.dec_avg_np_xg_rolling_5,  em.dec_avg_np_xg_rolling_10,
    em.dec_failed_to_score_rate_rolling_3, em.dec_failed_to_score_rate_rolling_5, em.dec_failed_to_score_rate_rolling_10,
    em.dec_win_rate_rolling_3,   em.dec_win_rate_rolling_5,   em.dec_win_rate_rolling_10,

    -- ── Contexte défensif de l'ADVERSAIRE (equipe_match sur opponent_id) ──────
    opp.dec_avg_np_xg_conceded_rolling_3  as opp_dec_avg_np_xg_conceded_rolling_3,
    opp.dec_avg_np_xg_conceded_rolling_5  as opp_dec_avg_np_xg_conceded_rolling_5,
    opp.dec_avg_np_xg_conceded_rolling_10 as opp_dec_avg_np_xg_conceded_rolling_10,
    opp.dec_clean_sheet_rate_rolling_3  as opp_dec_clean_sheet_rate_rolling_3,
    opp.dec_clean_sheet_rate_rolling_5  as opp_dec_clean_sheet_rate_rolling_5,
    opp.dec_clean_sheet_rate_rolling_10 as opp_dec_clean_sheet_rate_rolling_10,

    -- ── Priors de qualité de saison PRÉCÉDENTE (equipe_match, _lag) ───────────
    em.dec_season_xg_per_shot_for_lag,
    em.dec_season_xg_per_shot_against_lag,
    opp.dec_season_xg_per_shot_for_lag     as opp_dec_season_xg_per_shot_for_lag,
    opp.dec_season_xg_per_shot_against_lag as opp_dec_season_xg_per_shot_against_lag,

    case when pms.n_assists >= 1 then 1 else 0 end as int_assisted
from in_joueur_saison js
left join backbone_in                     b   using (match_id, team_id)
left join in_player_match_stats pms using (match_id, team_id, player_id)
left join {{ ref('equipe_match') }}       em  on em.str_match_id  = js.match_id and em.str_team_id  = cast(js.team_id as varchar)
left join {{ ref('equipe_match') }}       opp on opp.str_match_id = js.match_id and opp.str_team_id = b.str_opponent_id
),

mdl_out AS (
    SELECT
        "str_match_id"                                               AS str_match_id,
        "str_team_id"                                                AS str_team_id,
        "str_player_id"                                              AS str_player_id,
        "season"                                                     AS str_season,
        "is_home"                                                    AS bool_is_home,
        CAST(opponent_id AS VARCHAR)                                 AS str_opponent_id,
        "scorer_xg_per90_lag"                                        AS dec_scorer_xg_per90_lag,
        "scorer_shots_per90_lag"                                     AS dec_scorer_shots_per90_lag,
        "off_chances_created_per90_lag"                              AS dec_off_chances_created_per90_lag,
        "off_key_passes_per90_lag"                                   AS dec_off_key_passes_per90_lag,
        "off_xgchain_per90_lag"                                      AS dec_off_xgchain_per90_lag,
        "off_xgbuildup_per90_lag"                                    AS dec_off_xgbuildup_per90_lag,
        "n_apps_lag"                                                 AS int_n_apps_lag,
        CAST(minutes_lag AS BIGINT)                                  AS int_minutes_lag,
        CAST(scorer_freekick_taker_lag AS BIGINT)                    AS int_scorer_freekick_taker_lag,
        "profile_confidence_flag"                                    AS str_profile_confidence_flag,
        "dec_avg_np_xg_rolling_3"                                    AS dec_avg_np_xg_rolling_3,
        "dec_avg_np_xg_rolling_5"                                    AS dec_avg_np_xg_rolling_5,
        "dec_avg_np_xg_rolling_10"                                   AS dec_avg_np_xg_rolling_10,
        "dec_failed_to_score_rate_rolling_3"                         AS dec_failed_to_score_rate_rolling_3,
        "dec_failed_to_score_rate_rolling_5"                         AS dec_failed_to_score_rate_rolling_5,
        "dec_failed_to_score_rate_rolling_10"                        AS dec_failed_to_score_rate_rolling_10,
        "dec_win_rate_rolling_3"                                     AS dec_win_rate_rolling_3,
        "dec_win_rate_rolling_5"                                     AS dec_win_rate_rolling_5,
        "dec_win_rate_rolling_10"                                    AS dec_win_rate_rolling_10,
        "opp_dec_avg_np_xg_conceded_rolling_3"                       AS dec_opp_avg_np_xg_conceded_rolling_3,
        "opp_dec_avg_np_xg_conceded_rolling_5"                       AS dec_opp_avg_np_xg_conceded_rolling_5,
        "opp_dec_avg_np_xg_conceded_rolling_10"                      AS dec_opp_avg_np_xg_conceded_rolling_10,
        "opp_dec_clean_sheet_rate_rolling_3"                         AS dec_opp_clean_sheet_rate_rolling_3,
        "opp_dec_clean_sheet_rate_rolling_5"                         AS dec_opp_clean_sheet_rate_rolling_5,
        "opp_dec_clean_sheet_rate_rolling_10"                        AS dec_opp_clean_sheet_rate_rolling_10,
        "dec_season_xg_per_shot_for_lag"                             AS dec_season_xg_per_shot_for_lag,
        "dec_season_xg_per_shot_against_lag"                         AS dec_season_xg_per_shot_against_lag,
        "opp_dec_season_xg_per_shot_for_lag"                         AS dec_opp_season_xg_per_shot_for_lag,
        "opp_dec_season_xg_per_shot_against_lag"                     AS dec_opp_season_xg_per_shot_against_lag,
        "int_assisted"                                               AS int_assisted
    FROM mdl_body
)

SELECT * FROM mdl_out
