{{ config(materialized='table', schema='marts') }}

-- ══════════════════════════════════════════════════════════════════════════════
-- mart_events — grain (match_id) — cibles total_cards / total_corners (bruts ;
-- seuils fixés en config). Croise discipline + corners + coups francs des DEUX
-- équipes (profil d'équipe construit une fois, préfixé home_/away_).
--
-- Refonte nommage : backbone, equipe_match, rolling_corners et rolling_freekicks
-- sont lus sous leurs nouveaux noms (clés str_match_id / str_team_id partout, plus
-- de conversion de type). Les features héritent du nom de leur modèle source
-- (ex. home_dec_yellow_cards_rolling_3). Colonnes renommées selon
-- docs/proposition_nommage_definitif.csv : str_match_id, int_total_cards,
-- dec_total_corners.
-- ══════════════════════════════════════════════════════════════════════════════

-- ══ Refonte nommage (préfixe de type en tête de nom : str_, int_, dec_, dt_, bool_) ══
-- Entrées : les modèles amont refondus sont relus via des CTE in_<modèle> qui les
-- remappent vers les noms/types de travail utilisés par la logique ci-dessous
-- (inchangée). Sortie : CTE mdl_out, renommage + cast selon le type logique.

WITH

-- int_whoscored_player_match lu sous ses noms refondus, remappé vers les noms de travail du modèle
in_int_whoscored_player_match AS (
    SELECT
        str_match_id                                                 AS "match_id",
        CAST(str_team_id AS BIGINT)                                  AS "team_id",
        CAST(str_player_id AS INTEGER)                               AS "player_id",
        int_shirt_no                                                 AS "shirt_no",
        str_position                                                 AS "position",
        bool_is_first_eleven                                         AS "is_first_eleven",
        bool_is_man_of_the_match                                     AS "is_man_of_the_match",
        int_height                                                   AS "height",
        int_weight                                                   AS "weight",
        int_age                                                      AS "age",
        dec_rating                                                   AS "rating",
        str_stats_json                                               AS "stats_json",
        CAST(int_touches AS DOUBLE)                                  AS "touches",
        CAST(int_possession AS DOUBLE)                               AS "possession",
        CAST(int_passes_total AS DOUBLE)                             AS "passes_total",
        CAST(int_passes_accurate AS DOUBLE)                          AS "passes_accurate",
        CAST(int_passes_key AS DOUBLE)                               AS "passes_key",
        CAST(int_shots_total AS DOUBLE)                              AS "shots_total",
        CAST(int_shots_on_target AS DOUBLE)                          AS "shots_on_target",
        CAST(int_shots_off_target AS DOUBLE)                         AS "shots_off_target",
        CAST(int_shots_blocked AS DOUBLE)                            AS "shots_blocked",
        CAST(int_shots_on_post AS DOUBLE)                            AS "shots_on_post",
        CAST(int_dribbles_attempted AS DOUBLE)                       AS "dribbles_attempted",
        CAST(int_dribbles_won AS DOUBLE)                             AS "dribbles_won",
        CAST(int_dribbles_lost AS DOUBLE)                            AS "dribbles_lost",
        CAST(int_dribbled_past AS DOUBLE)                            AS "dribbled_past",
        CAST(int_dispossessed AS DOUBLE)                             AS "dispossessed",
        CAST(int_tackles_total AS DOUBLE)                            AS "tackles_total",
        CAST(int_tackle_successful AS DOUBLE)                        AS "tackle_successful",
        CAST(int_tackle_unsuccesful AS DOUBLE)                       AS "tackle_unsuccesful",
        CAST(int_interceptions AS DOUBLE)                            AS "interceptions",
        CAST(int_clearances AS DOUBLE)                               AS "clearances",
        CAST(int_aerials_total AS DOUBLE)                            AS "aerials_total",
        CAST(int_aerials_won AS DOUBLE)                              AS "aerials_won",
        CAST(int_offensive_aerials AS DOUBLE)                        AS "offensive_aerials",
        CAST(int_defensive_aerials AS DOUBLE)                        AS "defensive_aerials",
        CAST(int_fouls_commited AS DOUBLE)                           AS "fouls_commited",
        CAST(int_offsides_caught AS DOUBLE)                          AS "offsides_caught",
        CAST(int_errors AS DOUBLE)                                   AS "errors",
        CAST(int_corners_total AS DOUBLE)                            AS "corners_total",
        CAST(int_corners_accurate AS DOUBLE)                         AS "corners_accurate",
        CAST(int_throw_ins_total AS DOUBLE)                          AS "throw_ins_total",
        CAST(int_throw_ins_accurate AS DOUBLE)                       AS "throw_ins_accurate",
        CAST(int_total_saves AS DOUBLE)                              AS "total_saves",
        CAST(int_parried_safe AS DOUBLE)                             AS "parried_safe",
        CAST(int_parried_danger AS DOUBLE)                           AS "parried_danger",
        CAST(int_claims_high AS DOUBLE)                              AS "claims_high",
        CAST(int_collected AS DOUBLE)                                AS "collected"
    FROM {{ ref('int_whoscored_player_match') }}
),

-- rolling_corners lu sous ses noms refondus, remappé vers les noms de travail du modèle
in_rolling_corners AS (
    SELECT
        str_match_id                                                 AS "str_match_id",
        str_team_id                                                  AS "str_team_id",
        dt_date                                                      AS "dt_date",
        str_season                                                   AS "str_season",
        str_league_source                                            AS "str_league_source",
        CAST(int_corners_for_3 AS HUGEINT)                           AS "int_corners_for_3",
        dec_corner_danger_rate_for_3                                 AS "dec_corner_danger_rate_for_3",
        dec_corner_conversion_rate_for_3                             AS "dec_corner_conversion_rate_for_3",
        CAST(int_corners_against_3 AS HUGEINT)                       AS "int_corners_against_3",
        dec_corner_danger_rate_against_3                             AS "dec_corner_danger_rate_against_3",
        dec_corner_conversion_rate_against_3                         AS "dec_corner_conversion_rate_against_3",
        dec_corner_danger_intensity_for_3                            AS "dec_corner_danger_intensity_for_3",
        dec_corner_danger_intensity_against_3                        AS "dec_corner_danger_intensity_against_3",
        dec_corner_header_share_for_3                                AS "dec_corner_header_share_for_3",
        dec_corner_header_share_against_3                            AS "dec_corner_header_share_against_3",
        dec_corner_header_goal_share_for_3                           AS "dec_corner_header_goal_share_for_3",
        dec_corner_header_goal_share_against_3                       AS "dec_corner_header_goal_share_against_3",
        dec_corner_short_rate_for_3                                  AS "dec_corner_short_rate_for_3",
        dec_corner_short_rate_against_3                              AS "dec_corner_short_rate_against_3",
        dec_corner_forced_bad_clearance_rate_for_3                   AS "dec_corner_forced_bad_clearance_rate_for_3",
        dec_corner_clearance_fail_rate_against_3                     AS "dec_corner_clearance_fail_rate_against_3",
        dec_corner_headed_clearance_rate_against_3                   AS "dec_corner_headed_clearance_rate_against_3",
        CAST(int_corners_for_5 AS HUGEINT)                           AS "int_corners_for_5",
        dec_corner_danger_rate_for_5                                 AS "dec_corner_danger_rate_for_5",
        dec_corner_conversion_rate_for_5                             AS "dec_corner_conversion_rate_for_5",
        CAST(int_corners_against_5 AS HUGEINT)                       AS "int_corners_against_5",
        dec_corner_danger_rate_against_5                             AS "dec_corner_danger_rate_against_5",
        dec_corner_conversion_rate_against_5                         AS "dec_corner_conversion_rate_against_5",
        dec_corner_danger_intensity_for_5                            AS "dec_corner_danger_intensity_for_5",
        dec_corner_danger_intensity_against_5                        AS "dec_corner_danger_intensity_against_5",
        dec_corner_header_share_for_5                                AS "dec_corner_header_share_for_5",
        dec_corner_header_share_against_5                            AS "dec_corner_header_share_against_5",
        dec_corner_header_goal_share_for_5                           AS "dec_corner_header_goal_share_for_5",
        dec_corner_header_goal_share_against_5                       AS "dec_corner_header_goal_share_against_5",
        dec_corner_short_rate_for_5                                  AS "dec_corner_short_rate_for_5",
        dec_corner_short_rate_against_5                              AS "dec_corner_short_rate_against_5",
        dec_corner_forced_bad_clearance_rate_for_5                   AS "dec_corner_forced_bad_clearance_rate_for_5",
        dec_corner_clearance_fail_rate_against_5                     AS "dec_corner_clearance_fail_rate_against_5",
        dec_corner_headed_clearance_rate_against_5                   AS "dec_corner_headed_clearance_rate_against_5",
        CAST(int_corners_for_10 AS HUGEINT)                          AS "int_corners_for_10",
        dec_corner_danger_rate_for_10                                AS "dec_corner_danger_rate_for_10",
        dec_corner_conversion_rate_for_10                            AS "dec_corner_conversion_rate_for_10",
        CAST(int_corners_against_10 AS HUGEINT)                      AS "int_corners_against_10",
        dec_corner_danger_rate_against_10                            AS "dec_corner_danger_rate_against_10",
        dec_corner_conversion_rate_against_10                        AS "dec_corner_conversion_rate_against_10",
        dec_corner_danger_intensity_for_10                           AS "dec_corner_danger_intensity_for_10",
        dec_corner_danger_intensity_against_10                       AS "dec_corner_danger_intensity_against_10",
        dec_corner_header_share_for_10                               AS "dec_corner_header_share_for_10",
        dec_corner_header_share_against_10                           AS "dec_corner_header_share_against_10",
        dec_corner_header_goal_share_for_10                          AS "dec_corner_header_goal_share_for_10",
        dec_corner_header_goal_share_against_10                      AS "dec_corner_header_goal_share_against_10",
        dec_corner_short_rate_for_10                                 AS "dec_corner_short_rate_for_10",
        dec_corner_short_rate_against_10                             AS "dec_corner_short_rate_against_10",
        dec_corner_forced_bad_clearance_rate_for_10                  AS "dec_corner_forced_bad_clearance_rate_for_10",
        dec_corner_clearance_fail_rate_against_10                    AS "dec_corner_clearance_fail_rate_against_10",
        dec_corner_headed_clearance_rate_against_10                  AS "dec_corner_headed_clearance_rate_against_10"
    FROM {{ ref('rolling_corners') }}
),

-- rolling_freekicks lu sous ses noms refondus, remappé vers les noms de travail du modèle
in_rolling_freekicks AS (
    SELECT
        str_match_id                                                 AS "str_match_id",
        str_team_id                                                  AS "str_team_id",
        dt_date                                                      AS "dt_date",
        str_season                                                   AS "str_season",
        str_league_source                                            AS "str_league_source",
        CAST(int_freekicks_for_3 AS HUGEINT)                         AS "int_freekicks_for_3",
        dec_freekick_danger_rate_for_3                               AS "dec_freekick_danger_rate_for_3",
        dec_freekick_conversion_rate_for_3                           AS "dec_freekick_conversion_rate_for_3",
        CAST(int_freekicks_against_3 AS HUGEINT)                     AS "int_freekicks_against_3",
        dec_freekick_danger_rate_against_3                           AS "dec_freekick_danger_rate_against_3",
        dec_freekick_conversion_rate_against_3                       AS "dec_freekick_conversion_rate_against_3",
        dec_freekick_danger_intensity_for_3                          AS "dec_freekick_danger_intensity_for_3",
        dec_freekick_danger_intensity_against_3                      AS "dec_freekick_danger_intensity_against_3",
        dec_freekick_header_share_for_3                              AS "dec_freekick_header_share_for_3",
        dec_freekick_header_share_against_3                          AS "dec_freekick_header_share_against_3",
        dec_freekick_header_goal_share_for_3                         AS "dec_freekick_header_goal_share_for_3",
        dec_freekick_header_goal_share_against_3                     AS "dec_freekick_header_goal_share_against_3",
        dec_freekick_forced_bad_clearance_rate_for_3                 AS "dec_freekick_forced_bad_clearance_rate_for_3",
        dec_freekick_clearance_fail_rate_against_3                   AS "dec_freekick_clearance_fail_rate_against_3",
        dec_freekick_headed_clearance_rate_against_3                 AS "dec_freekick_headed_clearance_rate_against_3",
        dec_freekick_direct_distance_avg_for_3                       AS "dec_freekick_direct_distance_avg_for_3",
        dec_freekick_direct_distance_avg_against_3                   AS "dec_freekick_direct_distance_avg_against_3",
        dec_freekick_direct_angle_avg_for_3                          AS "dec_freekick_direct_angle_avg_for_3",
        dec_freekick_direct_angle_avg_against_3                      AS "dec_freekick_direct_angle_avg_against_3",
        dec_freekick_zone_direct_rate_for_3                          AS "dec_freekick_zone_direct_rate_for_3",
        dec_freekick_zone_direct_rate_against_3                      AS "dec_freekick_zone_direct_rate_against_3",
        dec_freekick_zone_crossed_rate_for_3                         AS "dec_freekick_zone_crossed_rate_for_3",
        dec_freekick_zone_crossed_rate_against_3                     AS "dec_freekick_zone_crossed_rate_against_3",
        CAST(int_freekicks_for_5 AS HUGEINT)                         AS "int_freekicks_for_5",
        dec_freekick_danger_rate_for_5                               AS "dec_freekick_danger_rate_for_5",
        dec_freekick_conversion_rate_for_5                           AS "dec_freekick_conversion_rate_for_5",
        CAST(int_freekicks_against_5 AS HUGEINT)                     AS "int_freekicks_against_5",
        dec_freekick_danger_rate_against_5                           AS "dec_freekick_danger_rate_against_5",
        dec_freekick_conversion_rate_against_5                       AS "dec_freekick_conversion_rate_against_5",
        dec_freekick_danger_intensity_for_5                          AS "dec_freekick_danger_intensity_for_5",
        dec_freekick_danger_intensity_against_5                      AS "dec_freekick_danger_intensity_against_5",
        dec_freekick_header_share_for_5                              AS "dec_freekick_header_share_for_5",
        dec_freekick_header_share_against_5                          AS "dec_freekick_header_share_against_5",
        dec_freekick_header_goal_share_for_5                         AS "dec_freekick_header_goal_share_for_5",
        dec_freekick_header_goal_share_against_5                     AS "dec_freekick_header_goal_share_against_5",
        dec_freekick_forced_bad_clearance_rate_for_5                 AS "dec_freekick_forced_bad_clearance_rate_for_5",
        dec_freekick_clearance_fail_rate_against_5                   AS "dec_freekick_clearance_fail_rate_against_5",
        dec_freekick_headed_clearance_rate_against_5                 AS "dec_freekick_headed_clearance_rate_against_5",
        dec_freekick_direct_distance_avg_for_5                       AS "dec_freekick_direct_distance_avg_for_5",
        dec_freekick_direct_distance_avg_against_5                   AS "dec_freekick_direct_distance_avg_against_5",
        dec_freekick_direct_angle_avg_for_5                          AS "dec_freekick_direct_angle_avg_for_5",
        dec_freekick_direct_angle_avg_against_5                      AS "dec_freekick_direct_angle_avg_against_5",
        dec_freekick_zone_direct_rate_for_5                          AS "dec_freekick_zone_direct_rate_for_5",
        dec_freekick_zone_direct_rate_against_5                      AS "dec_freekick_zone_direct_rate_against_5",
        dec_freekick_zone_crossed_rate_for_5                         AS "dec_freekick_zone_crossed_rate_for_5",
        dec_freekick_zone_crossed_rate_against_5                     AS "dec_freekick_zone_crossed_rate_against_5",
        CAST(int_freekicks_for_10 AS HUGEINT)                        AS "int_freekicks_for_10",
        dec_freekick_danger_rate_for_10                              AS "dec_freekick_danger_rate_for_10",
        dec_freekick_conversion_rate_for_10                          AS "dec_freekick_conversion_rate_for_10",
        CAST(int_freekicks_against_10 AS HUGEINT)                    AS "int_freekicks_against_10",
        dec_freekick_danger_rate_against_10                          AS "dec_freekick_danger_rate_against_10",
        dec_freekick_conversion_rate_against_10                      AS "dec_freekick_conversion_rate_against_10",
        dec_freekick_danger_intensity_for_10                         AS "dec_freekick_danger_intensity_for_10",
        dec_freekick_danger_intensity_against_10                     AS "dec_freekick_danger_intensity_against_10",
        dec_freekick_header_share_for_10                             AS "dec_freekick_header_share_for_10",
        dec_freekick_header_share_against_10                         AS "dec_freekick_header_share_against_10",
        dec_freekick_header_goal_share_for_10                        AS "dec_freekick_header_goal_share_for_10",
        dec_freekick_header_goal_share_against_10                    AS "dec_freekick_header_goal_share_against_10",
        dec_freekick_forced_bad_clearance_rate_for_10                AS "dec_freekick_forced_bad_clearance_rate_for_10",
        dec_freekick_clearance_fail_rate_against_10                  AS "dec_freekick_clearance_fail_rate_against_10",
        dec_freekick_headed_clearance_rate_against_10                AS "dec_freekick_headed_clearance_rate_against_10",
        dec_freekick_direct_distance_avg_for_10                      AS "dec_freekick_direct_distance_avg_for_10",
        dec_freekick_direct_distance_avg_against_10                  AS "dec_freekick_direct_distance_avg_against_10",
        dec_freekick_direct_angle_avg_for_10                         AS "dec_freekick_direct_angle_avg_for_10",
        dec_freekick_direct_angle_avg_against_10                     AS "dec_freekick_direct_angle_avg_against_10",
        dec_freekick_zone_direct_rate_for_10                         AS "dec_freekick_zone_direct_rate_for_10",
        dec_freekick_zone_direct_rate_against_10                     AS "dec_freekick_zone_direct_rate_against_10",
        dec_freekick_zone_crossed_rate_for_10                        AS "dec_freekick_zone_crossed_rate_for_10",
        dec_freekick_zone_crossed_rate_against_10                    AS "dec_freekick_zone_crossed_rate_against_10"
    FROM {{ ref('rolling_freekicks') }}
),

mdl_body AS (
with

matches as (
    select str_match_id,
        max(case when str_venue='Home' then str_team_id end) as home_team_id,
        max(case when str_venue='Away' then str_team_id end) as away_team_id,
        max(dt_date) as date, max(str_season) as season
    from {{ ref('backbone') }} where str_match_id is not null
    group by str_match_id
),

-- Cartons : NULL si les cartons d'une des deux équipes manquent (sum ignore les NULL,
-- comportement historique conservé).
label as (
    select str_match_id, sum(int_yellow_cards + coalesce(int_red_cards, 0)) as int_total_cards
    from {{ ref('backbone') }} where str_match_id is not null
    group by str_match_id
),

corners as (
    select match_id as str_match_id, sum(corners_total) as dec_total_corners
    from in_int_whoscored_player_match
    group by match_id
),

-- Profil événementiel d'une équipe : discipline + corners + coups francs.
team_events as (
    select em.str_match_id, em.str_team_id,
        em.dec_yellow_cards_rolling_3, em.dec_yellow_cards_rolling_5, em.dec_yellow_cards_rolling_10,
        em.dec_fouls_committed_rolling_3, em.dec_fouls_committed_rolling_5, em.dec_fouls_committed_rolling_10,
        rc.* exclude (str_match_id, str_team_id, dt_date, str_season, str_league_source),
        rf.* exclude (str_match_id, str_team_id, dt_date, str_season, str_league_source)
    from {{ ref('equipe_match') }} em
    left join in_rolling_corners   rc using (str_match_id, str_team_id)
    left join in_rolling_freekicks rf using (str_match_id, str_team_id)
),

home as (select columns('.*') as "home_\0" from team_events),
away as (select columns('.*') as "away_\0" from team_events)

select
    m.str_match_id, m.date, m.season,
    h.* exclude (home_str_match_id, home_str_team_id),
    a.* exclude (away_str_match_id, away_str_team_id),
    label.int_total_cards,
    corners.dec_total_corners
from matches m
left join home    h on h.home_str_match_id = m.str_match_id and h.home_str_team_id = m.home_team_id
left join away    a on a.away_str_match_id = m.str_match_id and a.away_str_team_id = m.away_team_id
left join label   using (str_match_id)
left join corners using (str_match_id)
),

mdl_out AS (
    SELECT
        "str_match_id"                                               AS str_match_id,
        "date"                                                       AS dt_date,
        "season"                                                     AS str_season,
        "home_dec_yellow_cards_rolling_3"                            AS dec_home_yellow_cards_rolling_3,
        "home_dec_yellow_cards_rolling_5"                            AS dec_home_yellow_cards_rolling_5,
        "home_dec_yellow_cards_rolling_10"                           AS dec_home_yellow_cards_rolling_10,
        "home_dec_fouls_committed_rolling_3"                         AS dec_home_fouls_committed_rolling_3,
        "home_dec_fouls_committed_rolling_5"                         AS dec_home_fouls_committed_rolling_5,
        "home_dec_fouls_committed_rolling_10"                        AS dec_home_fouls_committed_rolling_10,
        CAST(home_int_corners_for_3 AS BIGINT)                       AS int_home_corners_for_3,
        "home_dec_corner_danger_rate_for_3"                          AS dec_home_corner_danger_rate_for_3,
        "home_dec_corner_conversion_rate_for_3"                      AS dec_home_corner_conversion_rate_for_3,
        CAST(home_int_corners_against_3 AS BIGINT)                   AS int_home_corners_against_3,
        "home_dec_corner_danger_rate_against_3"                      AS dec_home_corner_danger_rate_against_3,
        "home_dec_corner_conversion_rate_against_3"                  AS dec_home_corner_conversion_rate_against_3,
        "home_dec_corner_danger_intensity_for_3"                     AS dec_home_corner_danger_intensity_for_3,
        "home_dec_corner_danger_intensity_against_3"                 AS dec_home_corner_danger_intensity_against_3,
        "home_dec_corner_header_share_for_3"                         AS dec_home_corner_header_share_for_3,
        "home_dec_corner_header_share_against_3"                     AS dec_home_corner_header_share_against_3,
        "home_dec_corner_header_goal_share_for_3"                    AS dec_home_corner_header_goal_share_for_3,
        "home_dec_corner_header_goal_share_against_3"                AS dec_home_corner_header_goal_share_against_3,
        "home_dec_corner_short_rate_for_3"                           AS dec_home_corner_short_rate_for_3,
        "home_dec_corner_short_rate_against_3"                       AS dec_home_corner_short_rate_against_3,
        "home_dec_corner_forced_bad_clearance_rate_for_3"            AS dec_home_corner_forced_bad_clearance_rate_for_3,
        "home_dec_corner_clearance_fail_rate_against_3"              AS dec_home_corner_clearance_fail_rate_against_3,
        "home_dec_corner_headed_clearance_rate_against_3"            AS dec_home_corner_headed_clearance_rate_against_3,
        CAST(home_int_corners_for_5 AS BIGINT)                       AS int_home_corners_for_5,
        "home_dec_corner_danger_rate_for_5"                          AS dec_home_corner_danger_rate_for_5,
        "home_dec_corner_conversion_rate_for_5"                      AS dec_home_corner_conversion_rate_for_5,
        CAST(home_int_corners_against_5 AS BIGINT)                   AS int_home_corners_against_5,
        "home_dec_corner_danger_rate_against_5"                      AS dec_home_corner_danger_rate_against_5,
        "home_dec_corner_conversion_rate_against_5"                  AS dec_home_corner_conversion_rate_against_5,
        "home_dec_corner_danger_intensity_for_5"                     AS dec_home_corner_danger_intensity_for_5,
        "home_dec_corner_danger_intensity_against_5"                 AS dec_home_corner_danger_intensity_against_5,
        "home_dec_corner_header_share_for_5"                         AS dec_home_corner_header_share_for_5,
        "home_dec_corner_header_share_against_5"                     AS dec_home_corner_header_share_against_5,
        "home_dec_corner_header_goal_share_for_5"                    AS dec_home_corner_header_goal_share_for_5,
        "home_dec_corner_header_goal_share_against_5"                AS dec_home_corner_header_goal_share_against_5,
        "home_dec_corner_short_rate_for_5"                           AS dec_home_corner_short_rate_for_5,
        "home_dec_corner_short_rate_against_5"                       AS dec_home_corner_short_rate_against_5,
        "home_dec_corner_forced_bad_clearance_rate_for_5"            AS dec_home_corner_forced_bad_clearance_rate_for_5,
        "home_dec_corner_clearance_fail_rate_against_5"              AS dec_home_corner_clearance_fail_rate_against_5,
        "home_dec_corner_headed_clearance_rate_against_5"            AS dec_home_corner_headed_clearance_rate_against_5,
        CAST(home_int_corners_for_10 AS BIGINT)                      AS int_home_corners_for_10,
        "home_dec_corner_danger_rate_for_10"                         AS dec_home_corner_danger_rate_for_10,
        "home_dec_corner_conversion_rate_for_10"                     AS dec_home_corner_conversion_rate_for_10,
        CAST(home_int_corners_against_10 AS BIGINT)                  AS int_home_corners_against_10,
        "home_dec_corner_danger_rate_against_10"                     AS dec_home_corner_danger_rate_against_10,
        "home_dec_corner_conversion_rate_against_10"                 AS dec_home_corner_conversion_rate_against_10,
        "home_dec_corner_danger_intensity_for_10"                    AS dec_home_corner_danger_intensity_for_10,
        "home_dec_corner_danger_intensity_against_10"                AS dec_home_corner_danger_intensity_against_10,
        "home_dec_corner_header_share_for_10"                        AS dec_home_corner_header_share_for_10,
        "home_dec_corner_header_share_against_10"                    AS dec_home_corner_header_share_against_10,
        "home_dec_corner_header_goal_share_for_10"                   AS dec_home_corner_header_goal_share_for_10,
        "home_dec_corner_header_goal_share_against_10"               AS dec_home_corner_header_goal_share_against_10,
        "home_dec_corner_short_rate_for_10"                          AS dec_home_corner_short_rate_for_10,
        "home_dec_corner_short_rate_against_10"                      AS dec_home_corner_short_rate_against_10,
        "home_dec_corner_forced_bad_clearance_rate_for_10"           AS dec_home_corner_forced_bad_clearance_rate_for_10,
        "home_dec_corner_clearance_fail_rate_against_10"             AS dec_home_corner_clearance_fail_rate_against_10,
        "home_dec_corner_headed_clearance_rate_against_10"           AS dec_home_corner_headed_clearance_rate_against_10,
        CAST(home_int_freekicks_for_3 AS BIGINT)                     AS int_home_freekicks_for_3,
        "home_dec_freekick_danger_rate_for_3"                        AS dec_home_freekick_danger_rate_for_3,
        "home_dec_freekick_conversion_rate_for_3"                    AS dec_home_freekick_conversion_rate_for_3,
        CAST(home_int_freekicks_against_3 AS BIGINT)                 AS int_home_freekicks_against_3,
        "home_dec_freekick_danger_rate_against_3"                    AS dec_home_freekick_danger_rate_against_3,
        "home_dec_freekick_conversion_rate_against_3"                AS dec_home_freekick_conversion_rate_against_3,
        "home_dec_freekick_danger_intensity_for_3"                   AS dec_home_freekick_danger_intensity_for_3,
        "home_dec_freekick_danger_intensity_against_3"               AS dec_home_freekick_danger_intensity_against_3,
        "home_dec_freekick_header_share_for_3"                       AS dec_home_freekick_header_share_for_3,
        "home_dec_freekick_header_share_against_3"                   AS dec_home_freekick_header_share_against_3,
        "home_dec_freekick_header_goal_share_for_3"                  AS dec_home_freekick_header_goal_share_for_3,
        "home_dec_freekick_header_goal_share_against_3"              AS dec_home_freekick_header_goal_share_against_3,
        "home_dec_freekick_forced_bad_clearance_rate_for_3"          AS dec_home_freekick_forced_bad_clearance_rate_for_3,
        "home_dec_freekick_clearance_fail_rate_against_3"            AS dec_home_freekick_clearance_fail_rate_against_3,
        "home_dec_freekick_headed_clearance_rate_against_3"          AS dec_home_freekick_headed_clearance_rate_against_3,
        "home_dec_freekick_direct_distance_avg_for_3"                AS dec_home_freekick_direct_distance_avg_for_3,
        "home_dec_freekick_direct_distance_avg_against_3"            AS dec_home_freekick_direct_distance_avg_against_3,
        "home_dec_freekick_direct_angle_avg_for_3"                   AS dec_home_freekick_direct_angle_avg_for_3,
        "home_dec_freekick_direct_angle_avg_against_3"               AS dec_home_freekick_direct_angle_avg_against_3,
        "home_dec_freekick_zone_direct_rate_for_3"                   AS dec_home_freekick_zone_direct_rate_for_3,
        "home_dec_freekick_zone_direct_rate_against_3"               AS dec_home_freekick_zone_direct_rate_against_3,
        "home_dec_freekick_zone_crossed_rate_for_3"                  AS dec_home_freekick_zone_crossed_rate_for_3,
        "home_dec_freekick_zone_crossed_rate_against_3"              AS dec_home_freekick_zone_crossed_rate_against_3,
        CAST(home_int_freekicks_for_5 AS BIGINT)                     AS int_home_freekicks_for_5,
        "home_dec_freekick_danger_rate_for_5"                        AS dec_home_freekick_danger_rate_for_5,
        "home_dec_freekick_conversion_rate_for_5"                    AS dec_home_freekick_conversion_rate_for_5,
        CAST(home_int_freekicks_against_5 AS BIGINT)                 AS int_home_freekicks_against_5,
        "home_dec_freekick_danger_rate_against_5"                    AS dec_home_freekick_danger_rate_against_5,
        "home_dec_freekick_conversion_rate_against_5"                AS dec_home_freekick_conversion_rate_against_5,
        "home_dec_freekick_danger_intensity_for_5"                   AS dec_home_freekick_danger_intensity_for_5,
        "home_dec_freekick_danger_intensity_against_5"               AS dec_home_freekick_danger_intensity_against_5,
        "home_dec_freekick_header_share_for_5"                       AS dec_home_freekick_header_share_for_5,
        "home_dec_freekick_header_share_against_5"                   AS dec_home_freekick_header_share_against_5,
        "home_dec_freekick_header_goal_share_for_5"                  AS dec_home_freekick_header_goal_share_for_5,
        "home_dec_freekick_header_goal_share_against_5"              AS dec_home_freekick_header_goal_share_against_5,
        "home_dec_freekick_forced_bad_clearance_rate_for_5"          AS dec_home_freekick_forced_bad_clearance_rate_for_5,
        "home_dec_freekick_clearance_fail_rate_against_5"            AS dec_home_freekick_clearance_fail_rate_against_5,
        "home_dec_freekick_headed_clearance_rate_against_5"          AS dec_home_freekick_headed_clearance_rate_against_5,
        "home_dec_freekick_direct_distance_avg_for_5"                AS dec_home_freekick_direct_distance_avg_for_5,
        "home_dec_freekick_direct_distance_avg_against_5"            AS dec_home_freekick_direct_distance_avg_against_5,
        "home_dec_freekick_direct_angle_avg_for_5"                   AS dec_home_freekick_direct_angle_avg_for_5,
        "home_dec_freekick_direct_angle_avg_against_5"               AS dec_home_freekick_direct_angle_avg_against_5,
        "home_dec_freekick_zone_direct_rate_for_5"                   AS dec_home_freekick_zone_direct_rate_for_5,
        "home_dec_freekick_zone_direct_rate_against_5"               AS dec_home_freekick_zone_direct_rate_against_5,
        "home_dec_freekick_zone_crossed_rate_for_5"                  AS dec_home_freekick_zone_crossed_rate_for_5,
        "home_dec_freekick_zone_crossed_rate_against_5"              AS dec_home_freekick_zone_crossed_rate_against_5,
        CAST(home_int_freekicks_for_10 AS BIGINT)                    AS int_home_freekicks_for_10,
        "home_dec_freekick_danger_rate_for_10"                       AS dec_home_freekick_danger_rate_for_10,
        "home_dec_freekick_conversion_rate_for_10"                   AS dec_home_freekick_conversion_rate_for_10,
        CAST(home_int_freekicks_against_10 AS BIGINT)                AS int_home_freekicks_against_10,
        "home_dec_freekick_danger_rate_against_10"                   AS dec_home_freekick_danger_rate_against_10,
        "home_dec_freekick_conversion_rate_against_10"               AS dec_home_freekick_conversion_rate_against_10,
        "home_dec_freekick_danger_intensity_for_10"                  AS dec_home_freekick_danger_intensity_for_10,
        "home_dec_freekick_danger_intensity_against_10"              AS dec_home_freekick_danger_intensity_against_10,
        "home_dec_freekick_header_share_for_10"                      AS dec_home_freekick_header_share_for_10,
        "home_dec_freekick_header_share_against_10"                  AS dec_home_freekick_header_share_against_10,
        "home_dec_freekick_header_goal_share_for_10"                 AS dec_home_freekick_header_goal_share_for_10,
        "home_dec_freekick_header_goal_share_against_10"             AS dec_home_freekick_header_goal_share_against_10,
        "home_dec_freekick_forced_bad_clearance_rate_for_10"         AS dec_home_freekick_forced_bad_clearance_rate_for_10,
        "home_dec_freekick_clearance_fail_rate_against_10"           AS dec_home_freekick_clearance_fail_rate_against_10,
        "home_dec_freekick_headed_clearance_rate_against_10"         AS dec_home_freekick_headed_clearance_rate_against_10,
        "home_dec_freekick_direct_distance_avg_for_10"               AS dec_home_freekick_direct_distance_avg_for_10,
        "home_dec_freekick_direct_distance_avg_against_10"           AS dec_home_freekick_direct_distance_avg_against_10,
        "home_dec_freekick_direct_angle_avg_for_10"                  AS dec_home_freekick_direct_angle_avg_for_10,
        "home_dec_freekick_direct_angle_avg_against_10"              AS dec_home_freekick_direct_angle_avg_against_10,
        "home_dec_freekick_zone_direct_rate_for_10"                  AS dec_home_freekick_zone_direct_rate_for_10,
        "home_dec_freekick_zone_direct_rate_against_10"              AS dec_home_freekick_zone_direct_rate_against_10,
        "home_dec_freekick_zone_crossed_rate_for_10"                 AS dec_home_freekick_zone_crossed_rate_for_10,
        "home_dec_freekick_zone_crossed_rate_against_10"             AS dec_home_freekick_zone_crossed_rate_against_10,
        "away_dec_yellow_cards_rolling_3"                            AS dec_away_yellow_cards_rolling_3,
        "away_dec_yellow_cards_rolling_5"                            AS dec_away_yellow_cards_rolling_5,
        "away_dec_yellow_cards_rolling_10"                           AS dec_away_yellow_cards_rolling_10,
        "away_dec_fouls_committed_rolling_3"                         AS dec_away_fouls_committed_rolling_3,
        "away_dec_fouls_committed_rolling_5"                         AS dec_away_fouls_committed_rolling_5,
        "away_dec_fouls_committed_rolling_10"                        AS dec_away_fouls_committed_rolling_10,
        CAST(away_int_corners_for_3 AS BIGINT)                       AS int_away_corners_for_3,
        "away_dec_corner_danger_rate_for_3"                          AS dec_away_corner_danger_rate_for_3,
        "away_dec_corner_conversion_rate_for_3"                      AS dec_away_corner_conversion_rate_for_3,
        CAST(away_int_corners_against_3 AS BIGINT)                   AS int_away_corners_against_3,
        "away_dec_corner_danger_rate_against_3"                      AS dec_away_corner_danger_rate_against_3,
        "away_dec_corner_conversion_rate_against_3"                  AS dec_away_corner_conversion_rate_against_3,
        "away_dec_corner_danger_intensity_for_3"                     AS dec_away_corner_danger_intensity_for_3,
        "away_dec_corner_danger_intensity_against_3"                 AS dec_away_corner_danger_intensity_against_3,
        "away_dec_corner_header_share_for_3"                         AS dec_away_corner_header_share_for_3,
        "away_dec_corner_header_share_against_3"                     AS dec_away_corner_header_share_against_3,
        "away_dec_corner_header_goal_share_for_3"                    AS dec_away_corner_header_goal_share_for_3,
        "away_dec_corner_header_goal_share_against_3"                AS dec_away_corner_header_goal_share_against_3,
        "away_dec_corner_short_rate_for_3"                           AS dec_away_corner_short_rate_for_3,
        "away_dec_corner_short_rate_against_3"                       AS dec_away_corner_short_rate_against_3,
        "away_dec_corner_forced_bad_clearance_rate_for_3"            AS dec_away_corner_forced_bad_clearance_rate_for_3,
        "away_dec_corner_clearance_fail_rate_against_3"              AS dec_away_corner_clearance_fail_rate_against_3,
        "away_dec_corner_headed_clearance_rate_against_3"            AS dec_away_corner_headed_clearance_rate_against_3,
        CAST(away_int_corners_for_5 AS BIGINT)                       AS int_away_corners_for_5,
        "away_dec_corner_danger_rate_for_5"                          AS dec_away_corner_danger_rate_for_5,
        "away_dec_corner_conversion_rate_for_5"                      AS dec_away_corner_conversion_rate_for_5,
        CAST(away_int_corners_against_5 AS BIGINT)                   AS int_away_corners_against_5,
        "away_dec_corner_danger_rate_against_5"                      AS dec_away_corner_danger_rate_against_5,
        "away_dec_corner_conversion_rate_against_5"                  AS dec_away_corner_conversion_rate_against_5,
        "away_dec_corner_danger_intensity_for_5"                     AS dec_away_corner_danger_intensity_for_5,
        "away_dec_corner_danger_intensity_against_5"                 AS dec_away_corner_danger_intensity_against_5,
        "away_dec_corner_header_share_for_5"                         AS dec_away_corner_header_share_for_5,
        "away_dec_corner_header_share_against_5"                     AS dec_away_corner_header_share_against_5,
        "away_dec_corner_header_goal_share_for_5"                    AS dec_away_corner_header_goal_share_for_5,
        "away_dec_corner_header_goal_share_against_5"                AS dec_away_corner_header_goal_share_against_5,
        "away_dec_corner_short_rate_for_5"                           AS dec_away_corner_short_rate_for_5,
        "away_dec_corner_short_rate_against_5"                       AS dec_away_corner_short_rate_against_5,
        "away_dec_corner_forced_bad_clearance_rate_for_5"            AS dec_away_corner_forced_bad_clearance_rate_for_5,
        "away_dec_corner_clearance_fail_rate_against_5"              AS dec_away_corner_clearance_fail_rate_against_5,
        "away_dec_corner_headed_clearance_rate_against_5"            AS dec_away_corner_headed_clearance_rate_against_5,
        CAST(away_int_corners_for_10 AS BIGINT)                      AS int_away_corners_for_10,
        "away_dec_corner_danger_rate_for_10"                         AS dec_away_corner_danger_rate_for_10,
        "away_dec_corner_conversion_rate_for_10"                     AS dec_away_corner_conversion_rate_for_10,
        CAST(away_int_corners_against_10 AS BIGINT)                  AS int_away_corners_against_10,
        "away_dec_corner_danger_rate_against_10"                     AS dec_away_corner_danger_rate_against_10,
        "away_dec_corner_conversion_rate_against_10"                 AS dec_away_corner_conversion_rate_against_10,
        "away_dec_corner_danger_intensity_for_10"                    AS dec_away_corner_danger_intensity_for_10,
        "away_dec_corner_danger_intensity_against_10"                AS dec_away_corner_danger_intensity_against_10,
        "away_dec_corner_header_share_for_10"                        AS dec_away_corner_header_share_for_10,
        "away_dec_corner_header_share_against_10"                    AS dec_away_corner_header_share_against_10,
        "away_dec_corner_header_goal_share_for_10"                   AS dec_away_corner_header_goal_share_for_10,
        "away_dec_corner_header_goal_share_against_10"               AS dec_away_corner_header_goal_share_against_10,
        "away_dec_corner_short_rate_for_10"                          AS dec_away_corner_short_rate_for_10,
        "away_dec_corner_short_rate_against_10"                      AS dec_away_corner_short_rate_against_10,
        "away_dec_corner_forced_bad_clearance_rate_for_10"           AS dec_away_corner_forced_bad_clearance_rate_for_10,
        "away_dec_corner_clearance_fail_rate_against_10"             AS dec_away_corner_clearance_fail_rate_against_10,
        "away_dec_corner_headed_clearance_rate_against_10"           AS dec_away_corner_headed_clearance_rate_against_10,
        CAST(away_int_freekicks_for_3 AS BIGINT)                     AS int_away_freekicks_for_3,
        "away_dec_freekick_danger_rate_for_3"                        AS dec_away_freekick_danger_rate_for_3,
        "away_dec_freekick_conversion_rate_for_3"                    AS dec_away_freekick_conversion_rate_for_3,
        CAST(away_int_freekicks_against_3 AS BIGINT)                 AS int_away_freekicks_against_3,
        "away_dec_freekick_danger_rate_against_3"                    AS dec_away_freekick_danger_rate_against_3,
        "away_dec_freekick_conversion_rate_against_3"                AS dec_away_freekick_conversion_rate_against_3,
        "away_dec_freekick_danger_intensity_for_3"                   AS dec_away_freekick_danger_intensity_for_3,
        "away_dec_freekick_danger_intensity_against_3"               AS dec_away_freekick_danger_intensity_against_3,
        "away_dec_freekick_header_share_for_3"                       AS dec_away_freekick_header_share_for_3,
        "away_dec_freekick_header_share_against_3"                   AS dec_away_freekick_header_share_against_3,
        "away_dec_freekick_header_goal_share_for_3"                  AS dec_away_freekick_header_goal_share_for_3,
        "away_dec_freekick_header_goal_share_against_3"              AS dec_away_freekick_header_goal_share_against_3,
        "away_dec_freekick_forced_bad_clearance_rate_for_3"          AS dec_away_freekick_forced_bad_clearance_rate_for_3,
        "away_dec_freekick_clearance_fail_rate_against_3"            AS dec_away_freekick_clearance_fail_rate_against_3,
        "away_dec_freekick_headed_clearance_rate_against_3"          AS dec_away_freekick_headed_clearance_rate_against_3,
        "away_dec_freekick_direct_distance_avg_for_3"                AS dec_away_freekick_direct_distance_avg_for_3,
        "away_dec_freekick_direct_distance_avg_against_3"            AS dec_away_freekick_direct_distance_avg_against_3,
        "away_dec_freekick_direct_angle_avg_for_3"                   AS dec_away_freekick_direct_angle_avg_for_3,
        "away_dec_freekick_direct_angle_avg_against_3"               AS dec_away_freekick_direct_angle_avg_against_3,
        "away_dec_freekick_zone_direct_rate_for_3"                   AS dec_away_freekick_zone_direct_rate_for_3,
        "away_dec_freekick_zone_direct_rate_against_3"               AS dec_away_freekick_zone_direct_rate_against_3,
        "away_dec_freekick_zone_crossed_rate_for_3"                  AS dec_away_freekick_zone_crossed_rate_for_3,
        "away_dec_freekick_zone_crossed_rate_against_3"              AS dec_away_freekick_zone_crossed_rate_against_3,
        CAST(away_int_freekicks_for_5 AS BIGINT)                     AS int_away_freekicks_for_5,
        "away_dec_freekick_danger_rate_for_5"                        AS dec_away_freekick_danger_rate_for_5,
        "away_dec_freekick_conversion_rate_for_5"                    AS dec_away_freekick_conversion_rate_for_5,
        CAST(away_int_freekicks_against_5 AS BIGINT)                 AS int_away_freekicks_against_5,
        "away_dec_freekick_danger_rate_against_5"                    AS dec_away_freekick_danger_rate_against_5,
        "away_dec_freekick_conversion_rate_against_5"                AS dec_away_freekick_conversion_rate_against_5,
        "away_dec_freekick_danger_intensity_for_5"                   AS dec_away_freekick_danger_intensity_for_5,
        "away_dec_freekick_danger_intensity_against_5"               AS dec_away_freekick_danger_intensity_against_5,
        "away_dec_freekick_header_share_for_5"                       AS dec_away_freekick_header_share_for_5,
        "away_dec_freekick_header_share_against_5"                   AS dec_away_freekick_header_share_against_5,
        "away_dec_freekick_header_goal_share_for_5"                  AS dec_away_freekick_header_goal_share_for_5,
        "away_dec_freekick_header_goal_share_against_5"              AS dec_away_freekick_header_goal_share_against_5,
        "away_dec_freekick_forced_bad_clearance_rate_for_5"          AS dec_away_freekick_forced_bad_clearance_rate_for_5,
        "away_dec_freekick_clearance_fail_rate_against_5"            AS dec_away_freekick_clearance_fail_rate_against_5,
        "away_dec_freekick_headed_clearance_rate_against_5"          AS dec_away_freekick_headed_clearance_rate_against_5,
        "away_dec_freekick_direct_distance_avg_for_5"                AS dec_away_freekick_direct_distance_avg_for_5,
        "away_dec_freekick_direct_distance_avg_against_5"            AS dec_away_freekick_direct_distance_avg_against_5,
        "away_dec_freekick_direct_angle_avg_for_5"                   AS dec_away_freekick_direct_angle_avg_for_5,
        "away_dec_freekick_direct_angle_avg_against_5"               AS dec_away_freekick_direct_angle_avg_against_5,
        "away_dec_freekick_zone_direct_rate_for_5"                   AS dec_away_freekick_zone_direct_rate_for_5,
        "away_dec_freekick_zone_direct_rate_against_5"               AS dec_away_freekick_zone_direct_rate_against_5,
        "away_dec_freekick_zone_crossed_rate_for_5"                  AS dec_away_freekick_zone_crossed_rate_for_5,
        "away_dec_freekick_zone_crossed_rate_against_5"              AS dec_away_freekick_zone_crossed_rate_against_5,
        CAST(away_int_freekicks_for_10 AS BIGINT)                    AS int_away_freekicks_for_10,
        "away_dec_freekick_danger_rate_for_10"                       AS dec_away_freekick_danger_rate_for_10,
        "away_dec_freekick_conversion_rate_for_10"                   AS dec_away_freekick_conversion_rate_for_10,
        CAST(away_int_freekicks_against_10 AS BIGINT)                AS int_away_freekicks_against_10,
        "away_dec_freekick_danger_rate_against_10"                   AS dec_away_freekick_danger_rate_against_10,
        "away_dec_freekick_conversion_rate_against_10"               AS dec_away_freekick_conversion_rate_against_10,
        "away_dec_freekick_danger_intensity_for_10"                  AS dec_away_freekick_danger_intensity_for_10,
        "away_dec_freekick_danger_intensity_against_10"              AS dec_away_freekick_danger_intensity_against_10,
        "away_dec_freekick_header_share_for_10"                      AS dec_away_freekick_header_share_for_10,
        "away_dec_freekick_header_share_against_10"                  AS dec_away_freekick_header_share_against_10,
        "away_dec_freekick_header_goal_share_for_10"                 AS dec_away_freekick_header_goal_share_for_10,
        "away_dec_freekick_header_goal_share_against_10"             AS dec_away_freekick_header_goal_share_against_10,
        "away_dec_freekick_forced_bad_clearance_rate_for_10"         AS dec_away_freekick_forced_bad_clearance_rate_for_10,
        "away_dec_freekick_clearance_fail_rate_against_10"           AS dec_away_freekick_clearance_fail_rate_against_10,
        "away_dec_freekick_headed_clearance_rate_against_10"         AS dec_away_freekick_headed_clearance_rate_against_10,
        "away_dec_freekick_direct_distance_avg_for_10"               AS dec_away_freekick_direct_distance_avg_for_10,
        "away_dec_freekick_direct_distance_avg_against_10"           AS dec_away_freekick_direct_distance_avg_against_10,
        "away_dec_freekick_direct_angle_avg_for_10"                  AS dec_away_freekick_direct_angle_avg_for_10,
        "away_dec_freekick_direct_angle_avg_against_10"              AS dec_away_freekick_direct_angle_avg_against_10,
        "away_dec_freekick_zone_direct_rate_for_10"                  AS dec_away_freekick_zone_direct_rate_for_10,
        "away_dec_freekick_zone_direct_rate_against_10"              AS dec_away_freekick_zone_direct_rate_against_10,
        "away_dec_freekick_zone_crossed_rate_for_10"                 AS dec_away_freekick_zone_crossed_rate_for_10,
        "away_dec_freekick_zone_crossed_rate_against_10"             AS dec_away_freekick_zone_crossed_rate_against_10,
        CAST(int_total_cards AS BIGINT)                              AS int_total_cards,
        CAST(dec_total_corners AS INTEGER)                           AS int_total_corners
    FROM mdl_body
)

SELECT * FROM mdl_out
